steps:
  # Paso 1: Construir imagen del backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/panaderia-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/panaderia-backend:latest',
      './backend'
    ]

  # Paso 2: Construir imagen del frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/panaderia-frontend:$BUILD_ID', 
      '-t', 'gcr.io/$PROJECT_ID/panaderia-frontend:latest',
      './frontend'
    ]

  # Paso 3: Push de imágenes al registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/panaderia-backend:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/panaderia-frontend:latest']

  # Paso 4: Deploy backend a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'panaderia-backend',
      '--image', 'gcr.io/$PROJECT_ID/panaderia-backend:latest',
      '--platform', 'managed',
      '--region', '$_REGION',
      '--allow-unauthenticated',
      '--add-cloudsql-instances', '$_CLOUDSQL_INSTANCE',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-secrets', 'DB_PASSWORD=db-password:latest'
    ]

  # Paso 5: Obtener URL del backend y deployar frontend con esa URL
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "📡 Obteniendo URL del backend..."
      BACKEND_URL=$$(gcloud run services describe panaderia-backend \
        --region=$_REGION \
        --format="value(status.url)")
      
      echo "🔗 Backend URL: $$BACKEND_URL"
      
      echo "🚀 Desplegando frontend con API URL: $$BACKEND_URL/api"
      gcloud run deploy panaderia-frontend \
        --image gcr.io/$PROJECT_ID/panaderia-frontend:latest \
        --platform managed \
        --region $_REGION \
        --allow-unauthenticated \
        --set-env-vars REACT_APP_API_URL=$$BACKEND_URL/api

substitutions:
  _REGION: 'us-central1'
  _CLOUDSQL_INSTANCE: 'PROJECT_ID:REGION:INSTANCE_NAME'

images:
  - 'gcr.io/$PROJECT_ID/panaderia-backend:latest'
  - 'gcr.io/$PROJECT_ID/panaderia-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
